### ISSUE TITLE
What version?

### ISSUE THREAD

**Issue by Denaton** [game-ci/steam-deploy#3]
Hi, I am currently making my first action but I can't run it because I don't know what I should type in \<version>\, where can I find it?

**Comment by webbertakken** [comment]
Heya @Denaton, and thanks for your interest in steam-deploy!

Please note that the action has not yet released any version, and that I still have a PR open to "Run command without errors". I'm currently stuck on 2 factor authentication. I will document the feature further once that is implemented. That said, it may already work for you, but it's still a work in progress for now.

As there is no version released, the only two options would be to use `master` which uses the latest commit in master or to use a specific commit. The first option will automatically update you to the latest version (but since there's no version yet you may expect breaking changes) whereas the second option will not receive any updates.

**Comment by webbertakken** [comment]
See also #4

**Comment by webbertakken** [comment]
Fixed by releasing [v0.1](https://github.com/game-ci/steam-deploy/releases/tag/v0.1). 🎉
